enhancer_dir: outputs/Jerman/bullitt_enhancer_jerman_2026-07-11_14-25-54
labels_dir: data/bullitt/labels
masks_dir: data/bullitt/masks
case_prefix: "patient_"
case_suffix: "_images.nii"
result_prefix: "results_patient_"
result_suffix: "_images.nii"
has_subdirs: false
patients:
  - "01"
  - "02"
  - "03"
  - "04"
  - "05"
  - "06"
  - "07"
  - "08"
  - "09"
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"
  - "15"
  - "16"
  - "17"
  - "18"
  - "19"
  - "20"
  - "21"
  - "22"
  - "23"
  - "24"
  - "25"
  - "26"
  - "27"
  - "28"
  - "29"
  - "30"
  - "31"
  - "32"
  - "33"
has_subdirs: false
